package vista;

public class iProducto extends javax.swing.JInternalFrame {
    
    

    public iProducto() {
        initComponents();
        this.setSize(500, 300);
        this.setTitle("Nuevo producto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_precio = new javax.swing.JLabel();
        lb_descripcion = new javax.swing.JLabel();
        lb_categoria = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        text_precio = new javax.swing.JTextField();
        text_descripcion = new javax.swing.JTextField();
        cbox_categoria = new javax.swing.JComboBox<>();
        btn_guardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_titulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lb_titulo.setText("NUEVO PRODUCTO");
        getContentPane().add(lb_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        lb_nombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lb_nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_nombre.setText("Nombre:");
        getContentPane().add(lb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, -1));

        lb_precio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_precio.setForeground(new java.awt.Color(0, 0, 0));
        lb_precio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_precio.setText("Precio:");
        getContentPane().add(lb_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, -1));

        lb_descripcion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_descripcion.setForeground(new java.awt.Color(0, 0, 0));
        lb_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_descripcion.setText("Descripción:");
        getContentPane().add(lb_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, -1));

        lb_categoria.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_categoria.setForeground(new java.awt.Color(0, 0, 0));
        lb_categoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_categoria.setText("Categoria:");
        getContentPane().add(lb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 110, -1));

        text_nombre.setBackground(new java.awt.Color(204, 204, 204));
        text_nombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text_nombre.setForeground(new java.awt.Color(0, 0, 0));
        text_nombre.setCaretColor(new java.awt.Color(0, 0, 0));
        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 350, -1));

        text_precio.setBackground(new java.awt.Color(204, 204, 204));
        text_precio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text_precio.setForeground(new java.awt.Color(0, 0, 0));
        text_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_precioActionPerformed(evt);
            }
        });
        getContentPane().add(text_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 350, -1));

        text_descripcion.setBackground(new java.awt.Color(204, 204, 204));
        text_descripcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text_descripcion.setForeground(new java.awt.Color(0, 0, 0));
        text_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(text_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 350, -1));

        cbox_categoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbox_categoria.setForeground(new java.awt.Color(0, 0, 0));
        cbox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoria", "Ciber", "Ciber - PROMOS", "Cocina", "Cocina - PROMOS", "Cafetería", "Cafeteria - PROMOS", "Jagertender", "Bebidas" }));
        cbox_categoria.setToolTipText("");
        getContentPane().add(cbox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 200, -1));

        btn_guardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(0, 0, 0));
        btn_guardar.setText("Guardar");
        btn_guardar.setToolTipText("");
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_precioActionPerformed

    private void text_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_descripcionActionPerformed

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cbox_categoria;
    private javax.swing.JLabel lb_categoria;
    private javax.swing.JLabel lb_descripcion;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_precio;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTextField text_descripcion;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_precio;
    // End of variables declaration//GEN-END:variables
}
